management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      serviceA:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 4
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 5s
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 10
        failureRateThreshold: 50
  retry:
    instances:
      serviceA:
        maxAttempts: 5
        waitDuration: 10s

  ratelimiter:
    instances:
      serviceA:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s


